
version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - LOG_FILE_ENV=/var/log/visits/visits.log
    volumes:
      - data:/var/log/visits/
volumes:
  data: