- name: Deploy app in docker
  tags: ["deploy app"]
  block:
    - name: Start docker
      service:
        name: docker
        state: started

    - name: Create app dir
      file:
        state: directory
        dest: "{{ app_path }}"

    - name: Pull app image from Docker registry
      docker_image:
        name: "{{ app_image_name }}"
        tag: "{{ app_image_tag }}"
        source: pull

    - name: Template a docker file
      ansible.builtin.template:
        src: docker-compose.yml
        dest: "{{ app_path }}/docker-compose.yml"

    - name: Run docker-compose
      ansible.builtin.docker_compose:
        project_src: "{{ app_path }}"
        state: present
